platform :ios,'8.0'
target ‘InKeLive’ do
pod 'AFNetworking'
pod 'MJRefresh', '~> 3.0.7'
pod 'SDWebImage', '~> 3.7.3'
pod 'MJExtension', '~> 3.0.13'
pod 'Masonry', '~> 1.0.2'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'ReactiveCocoa', '~> 2.4.7'
pod 'FMDB'
pod 'YYKit'
pod 'pop'
pod 'UMCCommon'
pod 'UMCAnalytics'
pod 'UMCSecurityPlugins'
pod 'ZYQAssetPickerController'


pod 'Reachability', '~> 3.2'
pod 'libksygpulive/libksygpulive'
pod 'pop'
end
