# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
pod ‘Masonry’
pod ‘MBProgressHUD’
pod ‘AFNetworking’
pod ‘Reachability’
pod ‘FMDB’
pod ‘pop’
pod ‘SDWebImage’
pod ‘STableViewController’
pod 'WechatOpenSDK'
pod ‘AMap2DMap’
pod ‘AMapSearch’
pod ‘AMapLocation’

target 'ChehuluHybrid' do

end

